<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>adress-book</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>Archetype - adress-book</name>
  <url>http://maven.apache.org</url>
  <properties>
  <maven.compiler.source>17</maven.compiler.source>
  <maven.compiler.target>17</maven.compiler.target>

  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <!-- SonarQube Configuration -->
  <sonar.host.url>http://localhost:9090</sonar.host.url>
  <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
  <sonar.coverage.jacoco.xmlReportPaths>
  target/site/jacoco/jacoco.xml
  </sonar.coverage.jacoco.xmlReportPaths>
  </properties>
  <build>
  <plugins>
  <!-- JaCoCo Plugin for Code Coverage -->
  <plugin>
  <groupId>org.jacoco</groupId>
  <artifactId>jacoco-maven-plugin</artifactId>
  <version>0.8.11</version>
  <executions>
  <execution>
  <id>prepare-agent</id>
  <goals>
  <goal>prepare-agent</goal>
  </goals>
  </execution>
  <execution>
  <id>report</id>
  <phase>test</phase>
  <goals>
  <goal>report</goal>
  </goals>
  </execution>
  </executions>
  </plugin>
  <!-- SonarQube Scanner Plugin -->
  <plugin>
  <groupId>org.sonarsource.scanner.maven</groupId>
  <artifactId>sonar-maven-plugin</artifactId>
  <version>3.10.0.2594</version>
  </plugin>
  </plugins>
  </build>
</project>
